services:
  postgres:
    image: postgres:17.6-alpine3.22
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  floci:
    image: floci/floci:latest
    ports:
      - "4566:4566"