services:
  postgres:
    image: postgres:17.6-alpine3.22
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"