services:
  postgres:
    image: postgres:17.6-alpine3.22
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  floci:
    image: floci/floci:latest
    ports:
      - "4566:4566"

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    depends_on:
      - postgres