CREATE SCHEMA IF NOT EXISTS garage;

-- ==========================================
-- TABLE: EMPLOYEE
-- ==========================================
CREATE TABLE garage.employee (
                                 id UUID NOT NULL,
                                 name VARCHAR(55) NOT NULL,
                                 created_at TIMESTAMP NOT NULL,
                                 updated_at TIMESTAMP,
                                 CONSTRAINT pk_employee PRIMARY KEY (id)
);

COMMENT ON COLUMN garage.employee.id IS 'Employee id. Owner: postgres';
COMMENT ON COLUMN garage.employee.name IS 'Employee name. Owner: self';
COMMENT ON COLUMN garage.employee.created_at IS 'Register created at. Owner: postgres';
COMMENT ON COLUMN garage.employee.updated_at IS 'Register updated at. Owner: postgres';

-- ==========================================
-- TABLE: ESTIMATE
-- ==========================================
CREATE TABLE garage.estimate (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                 amount NUMERIC NOT NULL,
                                 created_at TIMESTAMP NOT NULL,
                                 updated_at TIMESTAMP,
                                 CONSTRAINT pk_estimate PRIMARY KEY (id)
);

COMMENT ON COLUMN garage.estimate.id IS 'Estimate id. Owner: postgres';
COMMENT ON COLUMN garage.estimate.amount IS 'Estimate amount. Owner: self';
COMMENT ON COLUMN garage.estimate.created_at IS 'Register created at. Owner: postgres';
COMMENT ON COLUMN garage.estimate.updated_at IS 'Register updated at. Owner: postgres';

-- ==========================================
-- TABLE: INVENTORY
-- ==========================================
CREATE TABLE garage.inventory (
                                  id UUID NOT NULL,
                                  name VARCHAR(55) NOT NULL,
                                  price NUMERIC NOT NULL,
                                  quantity_in_stock INTEGER NOT NULL,
                                  created_at TIMESTAMP NOT NULL,
                                  updated_at TIMESTAMP,
                                  CONSTRAINT pk_inventory PRIMARY KEY (id)
);

COMMENT ON COLUMN garage.inventory.id IS 'Material id. Owner: postgres';
COMMENT ON COLUMN garage.inventory.name IS 'Inventory name. Owner: self';
COMMENT ON COLUMN garage.inventory.price IS 'Inventory price. Owner: self';
COMMENT ON COLUMN garage.inventory.quantity_in_stock IS 'Inventory quantity in stock. Owner: self';
COMMENT ON COLUMN garage.inventory.created_at IS 'Register created at. Owner: postgres';
COMMENT ON COLUMN garage.inventory.updated_at IS 'Register updated at. Owner: postgres';

-- ==========================================
-- TABLE: SHOP_SUPPLY (JOINED INHERITANCE)
-- ==========================================
CREATE TABLE garage.shop_supply (
                                    id UUID NOT NULL,
                                    CONSTRAINT pk_shop_supply PRIMARY KEY (id),
                                    CONSTRAINT fk_shop_supply_inventory FOREIGN KEY (id) REFERENCES garage.inventory(id) ON DELETE CASCADE
);

COMMENT ON TABLE garage.shop_supply IS 'Subclass table for ShopSupply extending Inventory';

-- ==========================================
-- TABLE: SPARE_PART (JOINED INHERITANCE)
-- ==========================================
CREATE TABLE garage.spare_part (
                                   id UUID NOT NULL,
                                   CONSTRAINT pk_spare_part PRIMARY KEY (id),
                                   CONSTRAINT fk_spare_part_inventory FOREIGN KEY (id) REFERENCES garage.inventory(id) ON DELETE CASCADE
);

COMMENT ON TABLE garage.spare_part IS 'Subclass table for SparePart extending Inventory';

-- ==========================================
-- TABLE: OWNER
-- ==========================================
CREATE TABLE garage.owner (
                              id UUID NOT NULL,
                              name VARCHAR(55) NOT NULL,
                              email VARCHAR(255) NOT NULL,
                              created_at TIMESTAMP NOT NULL,
                              updated_at TIMESTAMP,
                              CONSTRAINT pk_owner PRIMARY KEY (id)
);

COMMENT ON COLUMN garage.owner.id IS 'Owner id. Owner: postgres';
COMMENT ON COLUMN garage.owner.name IS 'Owner name. Owner: self';
COMMENT ON COLUMN garage.owner.email IS 'Owner e-mail. Owner: self';
COMMENT ON COLUMN garage.owner.created_at IS 'Register created at. Owner: postgres';
COMMENT ON COLUMN garage.owner.updated_at IS 'Register updated at. Owner: postgres';

-- ==========================================
-- TABLE: USER
-- ==========================================
CREATE TABLE garage."user" (
                               id UUID NOT NULL,
                               username VARCHAR(20) NOT NULL,
                               password VARCHAR(20) NOT NULL,
                               created_at TIMESTAMP NOT NULL,
                               updated_at TIMESTAMP,
                               CONSTRAINT pk_user PRIMARY KEY (id)
);

COMMENT ON COLUMN garage."user".id IS 'User id. Owner: postgres';
COMMENT ON COLUMN garage."user".username IS 'Username. Owner: self';
COMMENT ON COLUMN garage."user".password IS 'User password. Owner: self';
COMMENT ON COLUMN garage."user".created_at IS 'Register created at. Owner: postgres';
COMMENT ON COLUMN garage."user".updated_at IS 'Register updated at. Owner: postgres';

-- ==========================================
-- TABLE: AUTHORITY
-- ==========================================
CREATE TABLE garage.authority (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                  authority VARCHAR(20) NOT NULL,
                                  authority_id UUID NOT NULL, -- FK mapping defined by @JoinColumn in User.java
                                  created_at TIMESTAMP NOT NULL,
                                  updated_at TIMESTAMP,
                                  CONSTRAINT pk_authority PRIMARY KEY (id),
                                  CONSTRAINT fk_authority_user FOREIGN KEY (authority_id) REFERENCES garage."user"(id)
);

COMMENT ON COLUMN garage.authority.id IS 'Authorization id. Owner: postgres';
COMMENT ON COLUMN garage.authority.authority IS 'Authorization name. Owner: self';
COMMENT ON COLUMN garage.authority.authority_id IS 'Authority id.';
COMMENT ON COLUMN garage.authority.created_at IS 'Register created at. Owner: postgres';
COMMENT ON COLUMN garage.authority.updated_at IS 'Register updated at. Owner: postgres';

-- ==========================================
-- TABLE: VEHICLE
-- ==========================================
CREATE TABLE garage.vehicle (
                                id UUID NOT NULL,
                                make VARCHAR(55) NOT NULL,
                                model VARCHAR(55) NOT NULL,
                                license_plate VARCHAR(10) NOT NULL,
                                created_at TIMESTAMP NOT NULL,
                                updated_at TIMESTAMP,
                                CONSTRAINT pk_vehicle PRIMARY KEY (id)
);

COMMENT ON COLUMN garage.vehicle.id IS 'Vehicle id. Owner: postgres';
COMMENT ON COLUMN garage.vehicle.make IS 'Vehicle make. Owner: self';
COMMENT ON COLUMN garage.vehicle.model IS 'Vehicle model. Owner: self';
COMMENT ON COLUMN garage.vehicle.license_plate IS 'Vehicle license plate. Owner: self';
COMMENT ON COLUMN garage.vehicle.created_at IS 'Register created at. Owner: postgres';
COMMENT ON COLUMN garage.vehicle.updated_at IS 'Register updated at. Owner: postgres';

-- ==========================================
-- TABLE: WORK_ORDER
-- ==========================================
CREATE TABLE garage.work_order (
                                   id UUID NOT NULL,
                                   status VARCHAR(255) DEFAULT 'RECEIVED',
                                   estimate_id BIGINT,
                                   created_at TIMESTAMP NOT NULL,
                                   updated_at TIMESTAMP,
                                   CONSTRAINT pk_work_order PRIMARY KEY (id),
                                   CONSTRAINT fk_work_order_estimate FOREIGN KEY (estimate_id) REFERENCES garage.estimate(id)
);

COMMENT ON COLUMN garage.work_order.id IS 'WorkOrder id. Owner: postgres';
COMMENT ON COLUMN garage.work_order.status IS 'WorkOrder status. Owner: self';
COMMENT ON COLUMN garage.work_order.estimate_id IS 'Estimate id. Owner: postgres';
COMMENT ON COLUMN garage.work_order.created_at IS 'Register created at. Owner: postgres';
COMMENT ON COLUMN garage.work_order.updated_at IS 'Register updated at. Owner: postgres';