replicaCount: 1

image:
  repository: ""
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

env: {}

probes:
  enabled: false
  path: /actuator/health
  initialDelaySeconds: 20
  periodSeconds: 10
