terraform {
  required_providers {
    kind = {
      source  = "tehcyx/kind"
      version = "~> 0.8.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.23"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.12.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
  }
}

provider "kind" {}

provider "kubernetes" {
  host                   = kind_cluster.garage_cluster.endpoint
  client_certificate     = kind_cluster.garage_cluster.client_certificate
  client_key             = kind_cluster.garage_cluster.client_key
  cluster_ca_certificate = kind_cluster.garage_cluster.cluster_ca_certificate
}

provider "helm" {
  kubernetes {
    host                   = kind_cluster.garage_cluster.endpoint
    client_certificate     = kind_cluster.garage_cluster.client_certificate
    client_key             = kind_cluster.garage_cluster.client_key
    cluster_ca_certificate = kind_cluster.garage_cluster.cluster_ca_certificate
  }
}

output "kubeconfig_path" {
  description = "Path to the kubeconfig generated by the kind provider. Use: source iac/use-kubeconfig.sh"
  value       = kind_cluster.garage_cluster.kubeconfig_path
}