name: CI Pipeline

on:
  push:
    branches:
      - 'feature/**'

jobs:
#  code-quality:
#    runs-on: [self-hosted, local, k8s]
#
#    steps:
#      - name: Code checkout
#        uses: actions/checkout@v5
#
#      - name: Setup JDK
#        uses: ./.github/actions/setup-jdk
#
#      - name: Test and SonarQube analysis
#        run: |
#          mvn -B clean verify sonar:sonar \
#            -Dsonar.host.url=http://sonarqube:9000 \
#            -Dsonar.token=$SONAR_TOKEN \
#            -Dsonar.qualitygate.wait=true
#
#  integration-tests:
#    runs-on: [self-hosted, local, k8s]
#
#    steps:
#      - name: Code checkout
#        uses: actions/checkout@v5
#
#      - name: Setup JDK
#        uses: ./.github/actions/setup-jdk
#
#      - name: Run integration tests
#        run: mvn test -DintegrationTests
#
#  owasp-report:
#    runs-on: [self-hosted, local, k8s]
#    needs: [code-quality]
#
#    env:
#      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
#
#    steps:
#      - name: Code checkout
#        uses: actions/checkout@v5
#
#      - name: Setup JDK
#        uses: ./.github/actions/setup-jdk
#
#      - name: Generate OWASP Dependency-Check report
#        run: mvn -B clean verify -DskipTests -Dowasp -DdataDirectory=/root/.owasp/dependency-check/data
#
#      - name: Upload OWASP report
#        if: always()
#        uses: actions/upload-artifact@v7
#        with:
#          name: owasp-dependency-check-report
#          path: target/dependency-check-report.*
#          retention-days: 1

  build:
    runs-on: [ self-hosted, local, k8s ]
#    needs: [ owasp-report ]

    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: ./.github/actions/setup-jdk

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Build Docker image
        run: docker build -t api-garage:${{ github.sha }} -t api-garage:latest .

      - name: Load image into cluster containerd
        run: |
          # 1. Exporta a imagem gerada pelo dind usando a tag dinâmica do commit atual
          docker save -o api-garage.tar api-garage:${{ github.sha }}
          
          # 2. Cria o container dummy e extrai o ctr
          docker create --name ctrtump linuxkit/containerd:v0.7 sh
          docker cp ctrtump:/usr/bin/ctr ./ctr
          docker rm ctrtump
          chmod +x ./ctr
          
          # 3. Importa no containerd do nó do Kind usando o socket mapeado
          ./ctr -a /run/containerd/containerd.sock -n k8s.io images import api-garage.tar
          
          # 4. GARANTIA EXTRA: Força uma tag adicional "latest" no containerd do cluster para facilitar o debug
          ./ctr -a /run/containerd/containerd.sock -n k8s.io images tag api-garage:${{ github.sha }} api-garage:latest
          
          # 5. Limpa os arquivos temporários
          rm -f api-garage.tar ./ctr